name: CI/CD - Markify

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker compose -f docker-compose.yml build

      - name: Push Docker image to Docker Hub
        run: docker compose push

      - name: Create GitHub Deployment for Production
        id: deploy
        run: |
          response=$(curl -s -XPOST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"ref":"main","environment":"production"}' \
            https://api.github.com/repos/${{ github.repository }}/deployments)
          echo "RESPONSE=$response" >> $GITHUB_ENV
          deployment_id=$(echo $response | jq -r '.id')
          echo "deployment_id=$deployment_id" >> $GITHUB_ENV

      - name: Debug Deployment Response
        run: echo "Deployment Response: ${{ env.RESPONSE }}"

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            cd /root/CICD/Markify
            docker compose pull
            docker compose up -d

      - name: Set Deployment Status as Success
        run: |
          curl -XPATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"state":"success"}' \
          https://api.github.com/repos/${{ github.repository }}/deployments/${{ env.deployment_id }}
