name: CI/CD - Markify

on:
  push:
    branches:
      - main

# Add permissions for deployments
permissions:
  deployments: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker compose -f docker-compose.yml build

      - name: Push Docker image
        run: |
          echo "Pushing Docker image to Docker Hub..."
          docker compose push

      - name: Create GitHub Deployment for Production
        id: create_deployment
        run: |
          echo "Creating GitHub deployment for production..."
          RESPONSE=$(curl -s -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -d '{
              "ref":"main",
              "environment":"production",
              "auto_merge":false,
              "required_contexts":[]
            }' \
            https://api.github.com/repos/${{ github.repository }}/deployments)
          
          echo "GitHub API Response:"
          echo "$RESPONSE"

          DEPLOYMENT_ID=$(echo "$RESPONSE" | jq -r '.id')
          if [ "$DEPLOYMENT_ID" == "null" ] || [ -z "$DEPLOYMENT_ID" ]; then
            echo "Failed to create deployment. Response:"
            echo "$RESPONSE"
            exit 1
          fi
          echo "deployment_id=$DEPLOYMENT_ID" >> $GITHUB_OUTPUT

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            echo "Deploying application to VPS..."
            cd /root/CICD/Markify
            docker compose pull
            docker compose up -d

      - name: Set Deployment Status as Success
        run: |
          DEPLOYMENT_ID=${{ steps.create_deployment.outputs.deployment_id }}
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -d '{
              "state":"success",
              "description":"Deployment successful",
              "environment_url":"http://markify.rul.blue"
            }' \
            https://api.github.com/repos/${{ github.repository }}/deployments/$DEPLOYMENT_ID/statuses
